commerce_amazon_mws_order.settings:
  type: config_object
  label: 'Amazon MWS order settings'
  mapping:
    cron:
      type: mapping
      label: 'Cron settings'
      mapping:
        limit:
          type: int
          label: 'Limits the number of orders to import'
    billing_profile:
      type: mapping
      label: 'Billing profile settings'
      mapping:
        status:
          type: boolean
          label: 'Billing profile status'
        source:
          type: string
          label: 'Billing profile source'
        custom_address:
          type: mapping
          label: 'Custom billing information'
          mapping:
            country_code:
              type: string
              label: 'Country code'
            langcode:
              type: string
              label: 'Language code'
            given_name:
              type: string
              label: 'Given name'
            additional_name:
              type: string
              label: 'Additional name'
            family_name:
              type: string
              label: 'Family name'
            organization:
              type: string
              label: 'Organization'
            address_line1:
              type: string
              label: 'Address line 1'
            address_line2:
              type: string
              label: 'Address line 2'
            locality:
              type: string
              label: 'Locality'
            administrative_area:
              type: string
              label: 'Administrative area'
            dependent_locality:
              type: string
              label: 'Dependent locality'
            postal_code:
              type: string
              label: 'Postal code'
            sorting_code:
              type: string
              label: 'Sorting code'
