commerce_amws_product.settings:
  type: config_object
  label: 'Amazon MWS product settings'
  mapping:
    workflow:
      type: mapping
      label: 'Workflow settings'
      mapping:
        change_on_publish:
          type: boolean
          label: 'Mark as changed when published'
        change_on_commerce_product_change:
          type: boolean
          label: 'Mark as changed on associated commerce product change'
        queue_on_change:
          type: boolean
          label: 'Queue on change'
    cron:
      type: mapping
      label: 'Cron settings'
      mapping:
        status:
          type: boolean
          label: 'Cron status'
        store_limit:
          type: int
          label: 'Limits the number of stores to be processed'
        product_limit:
          type: int
          label: 'Limits the number of products per store to be exported'

commerce_amws_product.commerce_amws_product_type.*:
  type: config_entity
  label: 'Amazon MWS product type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: string
      label: 'Label'
    description:
      type: description
      label: 'Description'
    status:
      type: boolean
      label: 'Enabled'
    field_mapping:
      type: mapping
      label: 'Field mapping'
      mapping:
        commerce_amws_product_field:
          type: string
          label: 'Amazon MWS field name'
        commerce_product_field:
          type: string
          label: 'Drupal field name'
