commerce_amws_product.commerce_amws_product_type.*:
  type: config_entity
  label: 'Amazon MWS product type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: string
      label: 'Label'
    description:
      type: description
      label: 'Description'
    status:
      type: boolean
      label: 'Enabled'
    field_mapping:
      type: mapping
      label: 'Field mapping'
      mapping:
        commerce_oamws_product_field:
          type: string
          label: 'Amazon MWS field name'
        commerce_product_field:
          type: string
          label: 'Drupal field name'
